const crypto = require('crypto');

function required(name){const value=process.env[name];if(!value)throw new Error(`Configuration manquante : ${name}`);return value}
function config(){return {supabaseUrl:required('SUPABASE_URL').replace(/\/$/,''),serviceKey:required('SUPABASE_SERVICE_ROLE_KEY'),spotifyClientId:required('SPOTIFY_CLIENT_ID'),spotifyClientSecret:required('SPOTIFY_CLIENT_SECRET'),spotifyRedirectUri:required('SPOTIFY_REDIRECT_URI')}}
function adminEmails(){return (process.env.FIVES_ADMIN_EMAILS||'').split(',').map(value=>value.trim().toLowerCase()).filter(Boolean)}
function json(res,status,payload){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').send(JSON.stringify(payload))}
function encode(value){return encodeURIComponent(String(value))}
function scopeFrom(input){const leagueId=String(input?.leagueId||''),season=String(input?.season||'');if(!/^[0-9a-f-]{36}$/i.test(leagueId)||!/^[0-9]{4}-[0-9]{4}$/.test(season))throw new Error('Ligue ou saison invalide.');const leagueName=String(input?.leagueName||'Ligue').trim().slice(0,60)||'Ligue';return {leagueId,season,leagueName}}
async function serviceFetch(path,options={}){const cfg=config();return fetch(`${cfg.supabaseUrl}/rest/v1/${path}`,{...options,headers:{apikey:cfg.serviceKey,Authorization:`Bearer ${cfg.serviceKey}`,Accept:'application/json',...(options.headers||{})}})}
async function serviceJson(path,options={}){const response=await serviceFetch(path,options);const body=await response.text();if(!response.ok)throw new Error(`Base de données : ${body}`);return body?JSON.parse(body):null}
async function requireAdmin(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)throw new Error('Connexion administrateur requise.');const cfg=config();const response=await fetch(`${cfg.supabaseUrl}/auth/v1/user`,{headers:{apikey:cfg.serviceKey,Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('Session administrateur invalide.');const user=await response.json();if(!adminEmails().includes(String(user.email||'').toLowerCase()))throw new Error('Cette action est réservée aux administrateurs.');return user}
async function spotifyToken(body){const cfg=config();const response=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${cfg.spotifyClientId}:${cfg.spotifyClientSecret}`).toString('base64')}`,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error_description||'Autorisation Spotify refusée.');return payload}
async function spotifyRequest(path,token,options={}){const response=await fetch(`https://api.spotify.com/v1${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})}});const payload=response.status===204?null:await response.json();if(!response.ok)throw new Error(payload?.error?.message||'Spotify a refusé la requête.');return payload}
async function connection(){const rows=await serviceJson('spotify_connections?select=spotify_user_id,display_name,refresh_token&order=updated_at.desc&limit=1');return rows?.[0]||null}
async function accessToken(){const record=await connection();if(!record)throw new Error('Un administrateur doit d’abord connecter Spotify.');const token=await spotifyToken({grant_type:'refresh_token',refresh_token:record.refresh_token});return {token:token.access_token,connection:record}}
async function playlist(scope){const rows=await serviceJson(`spotify_playlists?select=spotify_playlist_id,spotify_playlist_url,name,owner_spotify_user_id&league_id=eq.${encode(scope.leagueId)}&season=eq.${encode(scope.season)}&limit=1`);return rows?.[0]||null}
async function createPlaylist(scope){const {token,connection:owner}=await accessToken();const name=`Fives League — ${scope.season}`;const created=await spotifyRequest('/me/playlists',token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description:'Playlist collaborative Fives League',public:true,collaborative:false})});const row={league_id:scope.leagueId,season:scope.season,spotify_playlist_id:created.id,spotify_playlist_url:created.external_urls.spotify,name:created.name,owner_spotify_user_id:owner.spotify_user_id};await serviceJson('spotify_playlists?on_conflict=league_id,season',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(row)});return {spotify_playlist_id:created.id,spotify_playlist_url:created.external_urls.spotify,name:created.name,owner_spotify_user_id:owner.spotify_user_id}}
function randomState(){return crypto.randomBytes(32).toString('hex')}
module.exports={config,json,scopeFrom,serviceFetch,serviceJson,requireAdmin,spotifyToken,spotifyRequest,connection,accessToken,playlist,createPlaylist,randomState};